document.write( '<table id="tablealine">')
document.write( '  <thead style="display: block;">')
document.write( '    <tr id="textbasyo">')
document.write( '    <th>一日韓国語表現<br>(準備中)</th>')
document.write( '    </tr>')
document.write( '    <tr>')
document.write( '      <td class="leversize">Level.1</tb>')
document.write( '        <td class="contnetsize">content</td>')
document.write( '    </tr>')

document.write( '    <tr>')
document.write( '      <td class="leversize">Level.2</tb>')
document.write( '        <td class="contnetsize">content</td>')
document.write( '    </tr>')
document.write( '    <tr>')
document.write( '      <td class="leversize">Level.3</tb>')
document.write( '        <td class="contnetsize">content</td>')
document.write( '    </tr>')
document.write( '    <tr>')
document.write( '      <td class="leversize">Level.4</tb>')
document.write( '        <td class="contnetsize">content</td>')
document.write( '    </tr>')

document.write( '    <tr>')
document.write( '      <td class="leversize">Level.5</tb>')
document.write( '        <td class="contnetsize">content</td>')
document.write( '    </tr>')
document.write( '  </thead>')
document.write( '</table>')
